language: java
jdk:
  - oraclejdk8
services:
  - mongodb
addons:
  postgresql: "9.3"
env:
  matrix:
    - MODULE=!querydsl-scala PROFILES=all,travis,examples
    - MODULE=!querydsl-scala PROFILES=all,travis,examples,hibernate5
    - MODULE=querydsl-scala PROFILES=all,travis
install:
  - mvn -B -q install -P${PROFILES} -DskipTests=true
before_script:
  - mysql -u root -e "source travis/mysql.sql"
  - psql -U postgres -f travis/postgresql.sql  
  - psql -c 'create extension postgis;' -d querydsl -U postgres
  - ./travis/cubrid.sh
  - ./travis/firebird.sh
script: mvn -B test -P${PROFILES} --projects ${MODULE} jacoco:report
sudo: required
after_success:
  - mvn coveralls:report
